# Generated by Django 5.2 on 2025-05-15 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('NI', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
                ('data_de_nascimento', models.DateField()),
                ('data_de_contratacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sala', models.CharField(max_length=15)),
                ('capacidade_de_pessoas', models.IntegerField()),
                ('localidade', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=100)),
                ('carga_horaria', models.TimeField()),
                ('descricao', models.CharField(max_length=300)),
                ('professor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaDeClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_inicio', models.DateField()),
                ('data_de_termino', models.DateField()),
                ('periodo', models.CharField(choices=[('D', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite'), ('N/A', 'Não Identificado')], default='N/A', max_length=3)),
                ('disciplina_associada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina')),
                ('professor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor')),
                ('sala_reservada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sala')),
            ],
        ),
    ]
